/*
 * BatchFileOpenPanel.java
 *
 * Created on June 30, 2008, 4:36 PM
 */

package com.webreach.mirth.client.ui;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  Erik Horstkotte
 */
public class BatchFileOpenPanel extends javax.swing.JPanel {
    
    private SpinnerNumberModel messageIndexModel = new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1);

    /** Creates new form BatchFileOpenPanel */
    public BatchFileOpenPanel() {
        initComponents();
        messageIndexSpinner.setModel(messageIndexModel);
    }

    public boolean isBatchProcess() {
        return batchProcessYesButton.isSelected();
    }

    public void setBatchProcess(boolean batchProcess) {
        batchProcessYesButton.setSelected(batchProcess);
    }
    
    public int getMessageIndex() {
        return messageIndexModel.getNumber().intValue();
    }
    
    public void setMessageIndex(int messageIndex) {
        messageIndexModel.setValue(new Integer(messageIndex));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        batchProcessLabel = new javax.swing.JLabel();
        batchProcessYesButton = new javax.swing.JRadioButton();
        batchProcessNoButton = new javax.swing.JRadioButton();
        messageIndexLabel = new javax.swing.JLabel();
        messageIndexSpinner = new javax.swing.JSpinner();

        batchProcessLabel.setText("Batch Process:");

        buttonGroup1.add(batchProcessYesButton);
        batchProcessYesButton.setSelected(true);
        batchProcessYesButton.setText("Yes");
        batchProcessYesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        batchProcessYesButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        batchProcessYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchProcessYesButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(batchProcessNoButton);
        batchProcessNoButton.setText("No");
        batchProcessNoButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        batchProcessNoButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        batchProcessNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchProcessNoButtonActionPerformed(evt);
            }
        });

        messageIndexLabel.setText("Load Message: ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(batchProcessLabel)
                    .add(messageIndexLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(batchProcessYesButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(batchProcessNoButton))
                    .add(messageIndexSpinner))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(batchProcessLabel)
                    .add(batchProcessYesButton)
                    .add(batchProcessNoButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(messageIndexLabel)
                    .add(messageIndexSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void batchProcessNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchProcessNoButtonActionPerformed
        messageIndexLabel.setEnabled(false);
        messageIndexSpinner.setEnabled(false);
    }//GEN-LAST:event_batchProcessNoButtonActionPerformed

    private void batchProcessYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchProcessYesButtonActionPerformed
        messageIndexLabel.setEnabled(true);
        messageIndexSpinner.setEnabled(true);
    }//GEN-LAST:event_batchProcessYesButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batchProcessLabel;
    private javax.swing.JRadioButton batchProcessNoButton;
    private javax.swing.JRadioButton batchProcessYesButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel messageIndexLabel;
    private javax.swing.JSpinner messageIndexSpinner;
    // End of variables declaration//GEN-END:variables
    
}
