package com.webreach.mirth.client.ui;

import java.util.prefs.Preferences;
import javax.swing.JFrame;

public class AdminPanel extends javax.swing.JPanel
{
    public Users u;

    private static Preferences userPreferences;
    private Frame parent;

    /** Creates new form AdminPanel */
    public AdminPanel()
    {
        this.parent = PlatformUI.MIRTH_FRAME;
        initComponents();
        u = new Users();
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(users);
        users.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(u, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(u, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        userPreferences = Preferences.systemNodeForPackage(Mirth.class);
        int interval = userPreferences.getInt("intervalTime", 20);
        intervalTime.setText(interval + "");
        intervalTime.setDocument(new MirthTextFieldLimit(3, false, true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        adminPanel = new javax.swing.JTabbedPane();
        users = new javax.swing.JPanel();
        settings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        intervalTime = new com.webreach.mirth.client.ui.MirthTextField();

        users.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                usersComponentShown(evt);
            }
        });

        org.jdesktop.layout.GroupLayout usersLayout = new org.jdesktop.layout.GroupLayout(users);
        users.setLayout(usersLayout);
        usersLayout.setHorizontalGroup(
            usersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 395, Short.MAX_VALUE)
        );
        usersLayout.setVerticalGroup(
            usersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 272, Short.MAX_VALUE)
        );
        adminPanel.addTab("Users", users);

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                settingsComponentShown(evt);
            }
        });

        jLabel1.setText("Refresh Interval Time (seconds):");

        org.jdesktop.layout.GroupLayout settingsLayout = new org.jdesktop.layout.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(intervalTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(settingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(intervalTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        adminPanel.addTab("Settings", settings);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, adminPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(adminPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void settingsComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_settingsComponentShown
    {//GEN-HEADEREND:event_settingsComponentShown
        parent.setFocus(parent.settingsTasks);
    }//GEN-LAST:event_settingsComponentShown

    private void usersComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_usersComponentShown
    {//GEN-HEADEREND:event_usersComponentShown
        parent.setFocus(parent.userTasks);
    }//GEN-LAST:event_usersComponentShown

    public void showTasks()
    {
        if(settings.isVisible())
        {
            parent.setFocus(parent.settingsTasks);
        }
        else
        {
            parent.setFocus(parent.userTasks);
        }
    }

    public void saveSettings()
    {
        userPreferences.putInt("intervalTime",Integer.parseInt(intervalTime.getText()));
        parent.settingsTasks.getContentPane().getComponent(0).setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane adminPanel;
    private com.webreach.mirth.client.ui.MirthTextField intervalTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel settings;
    private javax.swing.JPanel users;
    // End of variables declaration//GEN-END:variables

}
