package com.webreach.mirth.client.ui;

import java.util.Properties;

/** Used to extend from for all of the Connectors.
 *  Each method is re-implemented in each Connector.
 */
public class ConnectorClass extends javax.swing.JPanel
{
    String name;
    Properties properties = new Properties();    
    
    /** Creates new form ConnectorClass */
    public ConnectorClass()
    {
        initComponents();
    }
    
    /** Gets the name of the connector */
    public String getName()
    {
        return name;
    }
    
    /** Gets a properties object with all of the current data 
     *  in the connector's form.
     */
    public Properties getProperties()
    {
        return properties;
    }
    
    /** Sets all of the current data in the connector's form 
     *  to the data in the properties object parameter
     */
    public void setProperties(Properties props)
    {
    }
    
    /** NO LONGER USED.  Replaced by using setProperties(getDefaults()).
     *  Simply sets the defaults to everything int he form */
    public void setDefaults()
    {
    }
    
    /** Gets a properties object with all of the default settings
     *  for that form as the data.
     */
    public Properties getDefaults()
    {
        return properties;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
