/*
 * VariableList.java
 *
 * Created on June 21, 2006, 1:57 PM
 */

package com.webreach.mirth.client.ui;

import com.webreach.mirth.client.ui.transformeditor.TransformerPane;
import com.webreach.mirth.model.Step;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JList;

/**
 *
 * @author  brendanh
 */
public class VariableList extends javax.swing.JPanel
{
    
    /** Creates new form VariableList */
    public VariableList()
    {
        initComponents();
    }
    
    public void setVariableList(List<Step> steps)
    {
        String [] variables = new String[steps.size()];
        int i = 0;
        
        for (Iterator it = steps.iterator(); it.hasNext();)
        {
            Step step = (Step) it.next();
            Map data;
            if(step.getType().equalsIgnoreCase(TransformerPane.MAPPER_TYPE))
            {
                data = (Map)step.getData();
                variables[i] = (String)data.get("Variable");
                i++;
            }
        }
        
        jList1.removeAll();
        jList1.setListData(variables);
        
        jScrollPane1.setViewportView(jList1);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Variable List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        jList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
